# Site settings
name: Boyxu's Blog
email: xyj6989@gmail.com
author: Boyxu
url: https://boyxu.github.io
resume_site: https://boyxu.github.io/Resume.io/
github: https://github.com/boyxu
baseurl: ""
description: >- 
  iOS Developer
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 海纳百川，有容乃大；壁立千仞，无欲则刚
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: boyxu

# Build settings
markdown: kramdown

baidu_analysis: 27c528b5614ff0ae1011846356f6f352

revolvermaps: 5kx4948nr3v

plugins: 
    - jekyll-paginate
